apiVersion: v1
kind: Service
metadata:
    name: ms-listener-service
spec:
    selector:
        app: ms-listener
    type: NodePort 
    ports:
        - name: ms-listener-tcp
          protocol: TCP
          port: 9000
          targetPort: 9000
          nodePort: 30101
